### ISSUE TITLE
Balmer Events

### ISSUE THREAD

**Issue by NickDevoctomy** [MichaelGillett/MicrosoftCardGame#1]
More of an observation than anything, just been reading about this and looking at a picture of all the cards. Is Steve Balmer 0 on events ? Surely his sweaty "developers developers developers" scene should score a few event points? Lol

**Comment by MichaelGillett** [comment]
I decided that Ballmer doesn't get any Event squares because he doesn't do any events for Microsoft any more

**Comment by NickDevoctomy** [comment]
So this is a _live_ trumps system then, if someone quits now will you update it?

**Comment by MichaelGillett** [comment]
Possibly :)
